### ISSUE TITLE
CP2K duplicated keys an input generation

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmflows#92]
The following *CP2K* `Settings`:

```
general_settings:
  basis_name:
    "DZVP-MOLOPT-SR-GTH"
  path_basis:
    "/home/v13/cp2k_basis/BASIS_MOLOPT"
  path_potential:
    "/home/v13/cp2k_basis/GTH_POTENTIALS"
  scratch_path:
    "/scratch-shared/v13/Cd33Se33_test_new"
  settings_main:
    potential: "GTH-PBE"
    basis: "DZVP-MOLOPT-SR-GTH"
    cell_parameters: 28.0  
    cell_angles: [90.0, 90.0, 90.0]
    specific:
      cp2k:
        force_eval:
          subsys:
            cell:
              periodic: "None"
          dft:
            auxiliary_density_matrix_method: 
              method: "basis_projection"
              admm_purification_method: "mo_diag"
            poisson:
              periodic: "None"
              psolver: "MT" 
            qs: 
              method: "gpw"
              eps_pgf_orb: "1.0E-8"
            xc:
              xc_functional: 
                pbe: 
                  scale_x: "0.75"
                  scale_c: "1.00"
              hf:
                fraction: "0.25" 
                screening:
                  eps_schwarz: 1.0E-6
                  screen_on_initial_p: "True"
                memory:
                  max_memory: "5000"
                  eps_storage_scaling: "0.1"  
            scf:
              eps_scf: 0.0005
              max_scf: 200
              added_mos: 35
            print:
              mo:
                mo_index_range: "278 332"
```
Produced the following wrong input:
```
&FORCE_EVAL
  &DFT
    .....
    BASIS_SET_FILE_NAME  /home/v13/cp2k_basis/BASIS_MOLOPT
    POTENTIAL_FILE_NAME  /home/v13/cp2k_basis/GTH_POTENTIALS

    &XC_FUNCTIONAL pbe: 	
    scale_c: 	1.00
    scale_x: 	0.75
      &END
  &END
  &SUBSYS  
    .................
    &KIND  CD
      BASIS_SET  DZVP-MOLOPT-SR-GTH-q12
      POTENTIAL  GTH-PBE-q12
    &END
    &KIND  SE
      BASIS_SET  DZVP-MOLOPT-SR-GTH-q6
      POTENTIAL  GTH-PBE-q6
    &END
  &END
&END
......
```

The expected input is:
```
&GLOBAL
  PROJECT qmworks-cp2k         
  RUN_TYPE GEO_OPT
  PRINT_LEVEL LOW 
&END GLOBAL

&FORCE_EVAL
  METHOD Quickstep
  &DFT
    BASIS_SET_FILE_NAME /home/v13/cp2k_basis/BASIS_MOLOPT 
    BASIS_SET_FILE_NAME /home/v13/cp2k_basis/BASIS_ADMM_MOLOPT 
    POTENTIAL_FILE_NAME /home/v13/cp2k_basis/GTH_POTENTIALS
    &XC
      &XC_FUNCTIONAL PBE
        &PBE 
          SCALE_X 0.75 
          SCALE_C 1.00  # SUM UP ALWAYS TO 1.0 
        &END PBE
      &END XC_FUNCTIONAL
    &END XC
  &END DFT
 
  &SUBSYS
    &TOPOLOGY
      COORDINATE XYZ
      COORD_FILE_NAME ../Cd33Se33.xyz     
      &CENTER_COORDINATES
      &END
    &END TOPOLOGY
    &KIND Cd 
       BASIS_SET DZVP-MOLOPT-SR-GTH-q12
       AUX_FIT_BASIS_SET cFIT11
       POTENTIAL GTH-PBE-q12
    &END KIND
    &KIND Se 
       BASIS_SET DZVP-MOLOPT-SR-GTH-q6
       AUX_FIT_BASIS_SET cFIT9
       POTENTIAL GTH-PBE-q6
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
  ......................
```
